package io.acra.core.tests.sprint3;
import io.acra.core.analysis.semantic.*;
import io.acra.core.domain.authorization.*;
import io.acra.core.domain.finding.FindingFingerprint;
import io.acra.core.domain.http.*;
import io.acra.core.domain.testing.DifferentialTest;
import io.acra.core.engine.*;
import io.acra.core.openapi.*;
import io.acra.core.planning.*;
import io.acra.core.recon.*;
import io.acra.core.route.*;
import io.acra.core.tests.Fixtures;
import java.nio.charset.StandardCharsets;
import java.util.*;
public final class Sprint3CoreTestSuite {
    private static int tests;
    public static void main(String[] args){testSemanticIdentifiers();testParametersAndHeaders();testVersions();testRoutes();testOpenApiJson();testOpenApiYaml();testCorrelationAndDrift();testResponseSemantics();testPlanningAndCoverage();testDomainFoundations();testEndToEndRecon();System.out.println("PASS Sprint3 core tests="+tests);}
    private static void testSemanticIdentifiers(){var tx=Fixtures.tx("/api/v1/tenants/17/users/482/documents/991");var s=new SecurityContextEngine().analyze(tx);var ids=new SemanticIdentifierClassifier().classify(s.uri());check(ids.stream().anyMatch(i->i.candidate().value().equals("17")&&i.semanticType()==SemanticIdentifierType.TENANT_ID),"tenant id semantic");check(ids.stream().anyMatch(i->i.candidate().value().equals("482")&&i.semanticType()==SemanticIdentifierType.USER_ID),"user id semantic");check(ids.stream().anyMatch(i->i.candidate().value().equals("991")&&i.semanticType()==SemanticIdentifierType.RESOURCE_ID),"resource id semantic");tests+=3;}
    private static void testParametersAndHeaders(){var req=new HttpRequest(HttpMethod.GET,"https","api.test",443,"/documents?tenant_id=7&page=2&owner_id=42",List.of(new HttpHeader("X-Tenant-ID","7"),new HttpHeader("X-Original-URL","/internal"),new HttpHeader("Authorization","Bearer secret")),Map.of(),new byte[0],HttpProtocol.HTTP_1_1,new byte[0]);var tx=new HttpTransaction(req,new HttpResponse(200,List.of(),new byte[0],"",HttpProtocol.HTTP_1_1,new byte[0]),java.time.Instant.now(),"p-1","test",Map.of());var s=new SecurityContextEngine().analyze(tx);var p=new ParameterClassifier().classify(tx,s.uri());check(p.stream().anyMatch(x->x.name().equals("tenant_id")&&x.role()==ParameterRole.TENANT),"tenant query role");check(p.stream().anyMatch(x->x.name().equals("page")&&x.role()==ParameterRole.PAGINATION),"pagination role");check(p.stream().anyMatch(x->x.name().equals("owner_id")&&x.role()==ParameterRole.OWNER),"owner role");var h=new HeaderClassifier().classify(req.headers());check(h.stream().anyMatch(x->x.name().equals("X-Tenant-ID")&&x.role()==HeaderRole.TENANT),"tenant header");check(h.stream().anyMatch(x->x.name().equals("X-Original-URL")&&x.role()==HeaderRole.ROUTING),"routing header");check(h.stream().anyMatch(x->x.name().equals("Authorization")&&x.sensitive()),"auth sensitive");tests+=6;}
    private static void testVersions(){var req=HttpRequest.of(HttpMethod.GET,"https","api.test",443,"/v2/users?version=2026-08",List.of(new HttpHeader("X-API-Version","3")),new byte[0],HttpProtocol.HTTP_2);var tx=new HttpTransaction(req,new HttpResponse(200,List.of(),new byte[0],"",HttpProtocol.HTTP_2,new byte[0]),java.time.Instant.now(),"v-1","test",Map.of());var s=new SecurityContextEngine().analyze(tx);var v=new ApiVersionDiscovery().discover(tx,s.uri());check(v.stream().anyMatch(x->x.version().equals("v2")&&x.source().equals("path")),"path version");check(v.stream().anyMatch(x->x.version().equals("2026-08")&&x.source().startsWith("query")),"query version");check(v.stream().anyMatch(x->x.version().equals("3")&&x.source().startsWith("header")),"header version");tests+=3;}
    private static void testRoutes(){var e=new RouteTemplateEngine();check(e.parse("/users/{id}").syntax()==RouteSyntax.BRACE_TEMPLATE,"brace syntax");check(e.parse("/users/:id").syntax()==RouteSyntax.COLON_TEMPLATE,"colon syntax");check(e.parse("/users/*").syntax()==RouteSyntax.LITERAL_WILDCARD,"wildcard syntax");check(e.parse("/users/<int:id>").syntax()==RouteSyntax.ANGLE_TEMPLATE,"angle syntax");var eq=new RouteEquivalenceEngine();check(eq.compare("/users/{id}","/users/:id").kind()==RouteEquivalenceKind.CANONICALLY_EQUIVALENT,"framework templates equivalent");check(eq.compare("/users/{id}","/admin/{id}").kind()==RouteEquivalenceKind.DIFFERENT,"different static skeleton");tests+=6;}
    private static void testOpenApiJson(){String json="""
      {"openapi":"3.1.0","info":{"title":"Lab"},"components":{"securitySchemes":{"bearerAuth":{"type":"http","scheme":"bearer","bearerFormat":"JWT"}}},"paths":{"/api/v1/documents/{document_id}":{"get":{"operationId":"getDocument","tags":["documents"],"parameters":[{"name":"document_id","in":"path","required":true,"schema":{"type":"string"}}],"security":[{"bearerAuth":[]}],"responses":{"200":{},"403":{}}}}}}
      """;var d=new OpenApiImporter().importText(json,"inline");check(d.kind()==OpenApiSpecKind.OPENAPI_3,"openapi3 kind");check(d.operations().size()==1,"one operation");check(d.securitySchemes().containsKey("bearerAuth"),"security scheme");check(d.operations().getFirst().parameters().getFirst().name().equals("document_id"),"parameter parsed");check(d.operations().getFirst().responseCodes().contains("403"),"response parsed");tests+=5;}
    private static void testOpenApiYaml(){String y="""
openapi: 3.0.3
info:
  title: Lab YAML
paths:
  /api/v1/users/{user_id}:
    get:
      operationId: getUser
      parameters:
        - name: user_id
          in: path
          required: true
""";var d=new OpenApiImporter().importText(y,"yaml");check(d.kind()==OpenApiSpecKind.OPENAPI_3,"yaml openapi kind");check(d.operations().size()==1,"yaml operation");check(d.operations().getFirst().operationId().equals("getUser"),"yaml operation id");check(d.operations().getFirst().parameters().stream().anyMatch(p->p.name().equals("user_id")),"yaml parameter");tests+=4;}
    private static void testCorrelationAndDrift(){String json="{"+"\"openapi\":\"3.0.3\",\"paths\":{\"/api/v1/documents/{document_id}\":{\"get\":{\"parameters\":[{\"name\":\"document_id\",\"in\":\"path\",\"required\":true}],\"responses\":{\"200\":{}}}}}}";var spec=new OpenApiImporter().importText(json,"x");var s=new SecurityContextEngine().analyze(Fixtures.tx("/api/v1/documents/1001"));check(new OpenApiTrafficCorrelator().correlate(s.endpoint(),spec)==OpenApiCorrelationStatus.DOCUMENTED_OBSERVED,"correlation");var drift=new SchemaDriftAnalyzer().analyze(s.endpoint(),List.of(new ParameterIntelligence("debug",List.of("1"),io.acra.core.domain.uri.IdentifierLocation.QUERY,ParameterRole.UNKNOWN,io.acra.core.domain.common.Confidence.unknown(),"test")),Set.of(),Set.of("200"),spec);check(drift.stream().anyMatch(x->x.type()==SchemaDriftType.UNDOCUMENTED_PARAMETER),"drift unexpected param");tests+=2;}
    private static void testResponseSemantics(){var a=response("{\"id\":1001,\"owner_id\":42,\"tenant_id\":7,\"timestamp\":\"a\"}");var b=response("{\"tenant_id\":7,\"timestamp\":\"b\",\"owner_id\":42,\"id\":1001}");var x=new ResponseSemanticAnalyzer().fingerprint(a);var y=new ResponseSemanticAnalyzer().fingerprint(b);check(x.resourceIds().contains("1001"),"resource id response");check(x.ownerIds().contains("42"),"owner response");check(x.tenantIds().contains("7"),"tenant response");check(x.volatileFields().contains("timestamp"),"volatile timestamp");check(new ResourceSemanticMatcher().compare(x,y).sameResource(),"same resource despite order/dynamic");var denied=new ResponseSemanticAnalyzer().fingerprint(response("{\"success\":false,\"message\":\"Access denied\"}"));check(denied.responseClass()==SemanticResponseClass.ERROR_LIKE,"soft denial semantic");tests+=6;}
    private static void testPlanningAndCoverage(){var s=new SecurityContextEngine().analyze(Fixtures.tx("/api/v1/tenants/acme/documents/1001"));var r=new ApiReconnaissanceEngine().analyze(Fixtures.tx("/api/v1/tenants/acme/documents/1001"),s,null,List.of("user-a","user-b"),List.of("document:1001","document:1002"));check(r.reconnaissance().coverage().tenant(),"coverage tenant");check(r.dryRunPlan().dispatchedRequests()==0,"dry run dispatch zero");check(r.dryRunPlan().safetyNotes().contains("NO_NETWORK_REQUESTS"),"dry run safety");check(r.reconnaissance().priority().priority()!=EndpointPriority.UNKNOWN,"priority assigned");tests+=4;}
    private static void testDomainFoundations(){AuthorizationMatrix m=new AuthorizationMatrix();m.put(new AuthorizationMatrixEntry("a","viewer","t","doc:1","a","READ","GET /d/{id}",AuthorizationDecision.ALLOW,AuthorizationDecision.UNKNOWN,List.of("e1"),"OBSERVED"));check(m.size()==1,"matrix entry");var f1=FindingFingerprint.of("GET /d/{id}","doc:1","a","same-tenant","UNKNOWN","candidate");var f2=FindingFingerprint.of("GET /d/{id}","doc:1","a","same-tenant","UNKNOWN","candidate");check(f1.fingerprint().equals(f2.fingerprint()),"finding fingerprint deterministic");var d=new DifferentialTest("DT-1","A","B","none","ctx",AuthorizationDecision.UNKNOWN,AuthorizationDecision.UNKNOWN,List.of(),List.of(),0.0);check(d.testId().equals("DT-1"),"differential test model");tests+=3;}
    private static void testEndToEndRecon(){String token=Fixtures.jwt(Map.of("sub","user-a","tenant_id","tenant-a","role","editor"));var headers=List.of(new HttpHeader("Authorization","Bearer "+token),new HttpHeader("X-Tenant-ID","tenant-a"));var req=new HttpRequest(HttpMethod.PATCH,"https","api.example.test",443,"/api/v2/tenants/tenant-a/documents/1001?cursor=abc",headers,Map.of(),"{\"owner_id\":\"user-a\"}".getBytes(StandardCharsets.UTF_8),HttpProtocol.HTTP_2,new byte[0]);var res=response("{\"id\":\"1001\",\"owner_id\":\"user-a\",\"tenant_id\":\"tenant-a\",\"request_id\":\"x\"}");var tx=new HttpTransaction(req,res,java.time.Instant.parse("2026-08-31T00:00:00Z"),"S3-TX-1","test",Map.of());var s=new SecurityContextEngine().analyze(tx);var r=new ApiReconnaissanceEngine().analyze(tx,s,null,List.of("user-a","user-b"),List.of("document:1001","document:2001"));check(r.reconnaissance().parameters().stream().anyMatch(p->p.role()==ParameterRole.PAGINATION),"pagination intelligence");check(r.pagination().cursorBased(),"cursor model");check(r.securityContextFingerprint().principal().equals("user-a"),"fingerprint principal");check(r.responseFingerprint().ownerIds().contains("user-a"),"semantic owner");check(r.dryRunPlan().tests().stream().anyMatch(t->t.family()==TestFamily.TENANT_ISOLATION),"tenant test recommended");tests+=5;}
    private static HttpResponse response(String body){return new HttpResponse(200,List.of(new HttpHeader("Content-Type","application/json")),body.getBytes(StandardCharsets.UTF_8),"application/json",HttpProtocol.HTTP_1_1,new byte[0]);}
    private static void check(boolean v,String m){if(!v)throw new AssertionError(m);}
}
