package io.acra.burp.tests.sprint3;
import burp.api.montoya.core.*;
import burp.api.montoya.http.handler.*;
import burp.api.montoya.http.HttpService;
import burp.api.montoya.http.message.HttpHeader;
import burp.api.montoya.http.message.requests.HttpRequest;
import io.acra.burp.scope.*;
import io.acra.burp.traffic.*;
import io.acra.core.openapi.OpenApiCorrelationStatus;
import java.nio.charset.StandardCharsets;
import java.util.*;
public final class Sprint3AdapterTestSuite {
    private static int tests;
    public static void main(String[] args){testReconPipeline();testOpenApiCorrelation();testUnknownAndSafety();System.out.println("PASS Sprint3 adapter tests="+tests);}
    private static void testReconPipeline(){TrafficIntelligencePipeline p=new TrafficIntelligencePipeline(50);ScopeController scope=all();TrafficCollector c=new TrafficCollector(scope,p::process);FakeRequest r=req(1,"GET","/api/v2/tenants/tenant-a/documents/1001?cursor=abc",List.of(new Header("X-Tenant-ID","tenant-a")));c.onRequest(r);c.onResponse(res(1,r,200,"{\"id\":\"1001\",\"owner_id\":\"user-a\",\"tenant_id\":\"tenant-a\",\"request_id\":\"volatile\"}"));check(p.reconnaissanceStore().size()==1,"recon stored");var x=p.reconnaissanceStore().get("ACRA-TX-000001").orElseThrow();check(x.pagination().cursorBased(),"pagination detected");check(x.reconnaissance().versions().stream().anyMatch(v->v.version().equals("v2")),"version detected");check(x.responseFingerprint().ownerIds().contains("user-a"),"owner semantic response");check(x.dryRunPlan().dispatchedRequests()==0,"dry run only");tests+=5;}
    private static void testOpenApiCorrelation(){TrafficIntelligencePipeline p=new TrafficIntelligencePipeline(50);String spec="{\"openapi\":\"3.1.0\",\"paths\":{\"/api/v1/documents/{document_id}\":{\"get\":{\"responses\":{\"200\":{}}}}}}";new OpenApiImportService(p).importText(spec,"test");TrafficCollector c=new TrafficCollector(all(),p::process);FakeRequest r=req(2,"GET","/api/v1/documents/1001",List.of());c.onRequest(r);c.onResponse(res(2,r,200,"{\"id\":\"1001\"}"));var x=p.reconnaissanceStore().get("ACRA-TX-000001").orElseThrow();check(x.reconnaissance().documentationStatus()==OpenApiCorrelationStatus.DOCUMENTED_OBSERVED,"documented observed");check(x.reconnaissance().coverage().schema(),"schema coverage");check(x.schemaDrift().isEmpty(),"no endpoint drift");tests+=3;}
    private static void testUnknownAndSafety(){TrafficIntelligencePipeline p=new TrafficIntelligencePipeline(10);TrafficCollector c=new TrafficCollector(all(),p::process);FakeRequest r=req(3,"GET","/health?foo=bar",List.of(new Header("X-Strange","x")));c.onRequest(r);c.onResponse(res(3,r,200,"ok"));var x=p.reconnaissanceStore().get("ACRA-TX-000001").orElseThrow();check(x.reconnaissance().parameters().stream().anyMatch(q->q.name().equals("foo")&&q.role()==io.acra.core.recon.ParameterRole.UNKNOWN),"unknown parameter stays unknown");check(x.dryRunPlan().dispatchedRequests()==0,"no dispatch");check(!x.dryRunPlan().safetyNotes().isEmpty(),"safety notes");tests+=3;}
    private static ScopeController all(){ScopeController s=new ScopeController();s.update(new ScopeConfiguration(ScopeMode.ALL_TRAFFIC,List.of(),1024*1024,100,1,1,1000,false));return s;}
    private static FakeRequest req(int id,String method,String path,List<HttpHeader> extra){List<HttpHeader> h=new ArrayList<>();h.add(new Header("Host","api.lab"));h.add(new Header("Accept","application/json"));h.addAll(extra);return new FakeRequest(id,method,path,new byte[0],h);}
    private static FakeResponse res(int id,FakeRequest req,int status,String body){return new FakeResponse(id,req,(short)status,body.getBytes(StandardCharsets.UTF_8),List.of(new Header("Content-Type","application/json")));}
    private static void check(boolean v,String m){if(!v)throw new AssertionError(m);}
    private record Header(String name,String value) implements HttpHeader {}
    private record Bytes(byte[] bytes) implements ByteArray {public byte[] getBytes(){return bytes.clone();}public int length(){return bytes.length;}}
    private static final class Service implements HttpService {public String host(){return "api.lab";}public int port(){return 443;}public boolean secure(){return true;}}
    private static final class Source implements ToolSource {public ToolType toolType(){return ToolType.PROXY;}}
    private static final class FakeRequest implements HttpRequestToBeSent {private final int id;private final String method,path;private final byte[] body;private final List<HttpHeader> headers;FakeRequest(int id,String method,String path,byte[] body,List<HttpHeader> headers){this.id=id;this.method=method;this.path=path;this.body=body.clone();this.headers=List.copyOf(headers);}public int messageId(){return id;}public boolean isInScope(){return true;}public ToolSource toolSource(){return new Source();}public String method(){return method;}public String path(){return path;}public String pathWithoutQuery(){int q=path.indexOf('?');return q<0?path:path.substring(0,q);}public String httpVersion(){return "HTTP/1.1";}public List<HttpHeader> headers(){return headers;}public ByteArray body(){return new Bytes(body);}public ByteArray toByteArray(){return new Bytes((method+" "+path+" HTTP/1.1\r\n\r\n").getBytes(StandardCharsets.UTF_8));}public HttpService httpService(){return new Service();}}
    private static final class FakeResponse implements HttpResponseReceived {private final int id;private final HttpRequest req;private final short status;private final byte[] body;private final List<HttpHeader> headers;FakeResponse(int id,HttpRequest req,short status,byte[] body,List<HttpHeader> headers){this.id=id;this.req=req;this.status=status;this.body=body.clone();this.headers=List.copyOf(headers);}public int messageId(){return id;}public HttpRequest initiatingRequest(){return req;}public ToolSource toolSource(){return new Source();}public short statusCode(){return status;}public String httpVersion(){return "HTTP/1.1";}public List<HttpHeader> headers(){return headers;}public String headerValue(String name){return headers.stream().filter(h->h.name().equalsIgnoreCase(name)).map(HttpHeader::value).findFirst().orElse(null);}public ByteArray body(){return new Bytes(body);}public ByteArray toByteArray(){return new Bytes(body);}}
}
