package io.acra.core.active.model;

public enum MutationType {
    IDENTITY_SUBSTITUTION,
    ROLE_SUBSTITUTION,
    AUTHENTICATED_CONTEXT_SUBSTITUTION,
    TENANT_SUBSTITUTION,
    RESOURCE_SUBSTITUTION,
    REPRESENTATION_VARIATION,
    ENCODING_REPRESENTATION,
    NORMALIZATION_REPRESENTATION,
    EQUIVALENT_ROUTE_REPRESENTATION,
    METHOD_REPRESENTATION,
    PROPERTY,
    COLLECTION,
    BATCH,
    WORKFLOW_TRANSITION
}
