package io.acra.core.active.planning;

import io.acra.core.active.model.Mutation;
import io.acra.core.active.model.MutationLocation;
import io.acra.core.active.model.MutationType;
import io.acra.core.active.model.SafetyClass;
import io.acra.core.active.model.TestContract;
import io.acra.core.domain.authorization.AuthorizationDecision;
import io.acra.core.domain.authorization.PolicyResolutionState;
import io.acra.core.domain.http.HttpMethod;
import io.acra.core.domain.workflow.WorkflowAuthorizationResolution;
import io.acra.core.security.TokenFingerprint;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

/** Generates only a one-variable target-state mutation from explicit S7 workflow policy. */
public final class S7WorkflowTestSeedFactory {

    public S7WorkflowSeedGenerationResult generate(S7WorkflowPlanningCandidate candidate) {
        if (candidate == null) throw new IllegalArgumentException("candidate required");
        List<TestSeed> seeds = new ArrayList<>();
        List<String> skipped = new ArrayList<>();

        if (!candidate.allowedContracts().contains(TestContract.TRANSITION)) {
            skipped.add(candidate.candidateId() + ":TRANSITION_CONTRACT_DISABLED");
            return new S7WorkflowSeedGenerationResult(seeds, skipped);
        }
        if (!resolvable(candidate.baselineResolution()) || !resolvable(candidate.targetResolution())) {
            skipped.add(candidate.candidateId() + ":WORKFLOW_POLICY_UNRESOLVED");
            return new S7WorkflowSeedGenerationResult(seeds, skipped);
        }
        if (candidate.baselineResolution().expectedDecision() != AuthorizationDecision.ALLOW) {
            skipped.add(candidate.candidateId() + ":BASELINE_TRANSITION_NOT_EXPLICITLY_ALLOWED");
            return new S7WorkflowSeedGenerationResult(seeds, skipped);
        }
        if (candidate.endpoint().method() == HttpMethod.DELETE) {
            skipped.add(candidate.candidateId() + ":DESTRUCTIVE_METHOD_NOT_AUTOGENERATED");
            return new S7WorkflowSeedGenerationResult(seeds, skipped);
        }
        if (!sameTransitionContext(candidate.baselineResolution(), candidate.targetResolution())) {
            skipped.add(candidate.candidateId() + ":MUTATION_CHANGES_MORE_THAN_TARGET_STATE");
            return new S7WorkflowSeedGenerationResult(seeds, skipped);
        }
        String sourceState = candidate.baselineResolution().toState();
        String targetState = candidate.targetResolution().toState();
        if (sourceState.isBlank() || targetState.isBlank() || sourceState.equals(targetState)) {
            skipped.add(candidate.candidateId() + ":TARGET_STATE_NOT_DISTINCT");
            return new S7WorkflowSeedGenerationResult(seeds, skipped);
        }
        String body = new String(candidate.baseline().request().body(), StandardCharsets.UTF_8);
        if (occurrences(body, sourceState) != 1) {
            skipped.add(candidate.candidateId() + ":BASELINE_BODY_DOES_NOT_CONTAIN_ONE_SOURCE_TARGET_STATE");
            return new S7WorkflowSeedGenerationResult(seeds, skipped);
        }

        String key = candidate.targetResolution().policyFingerprint() + "|" + candidate.endpoint().endpointId()
                + "|" + candidate.targetResolution().workflowId() + "|" + candidate.targetResolution().action()
                + "|" + candidate.targetResolution().fromState() + "|" + sourceState + "->" + targetState;
        String suffix = TokenFingerprint.sha256(key).substring(0, 24);
        Mutation mutation = new Mutation(
                "S7-MUT-WORKFLOW-" + suffix,
                MutationType.WORKFLOW_TRANSITION,
                MutationLocation.BODY,
                sourceState,
                targetState,
                candidate.baseline().contextRef(),
                candidate.targetContext().principal() + "|" + candidate.targetContext().tenant()
                        + "|" + candidate.targetContext().role(),
                "single-variable workflow target-state substitution from explicit S7 policy",
                "target workflow policy expects " + candidate.targetResolution().expectedDecision(),
                SafetyClass.STATE_CHANGING,
                "s7-workflow:" + suffix);

        List<String> invariants = new ArrayList<>(candidate.invariants());
        invariants.add("workflowId, principal, tenant, resource, action and from-state remain unchanged");
        invariants.add("only the declared workflow target-state value is mutated");
        invariants.add("raw authentication material is never copied into Mutation");
        invariants.add("workflow policy fingerprint=" + candidate.targetResolution().policyFingerprint());

        seeds.add(new TestSeed(
                "S7-AUTO-WORKFLOW-" + suffix,
                "1",
                TestContract.TRANSITION,
                candidate.endpoint(),
                candidate.baseline(),
                candidate.positiveControl(),
                candidate.negativeControl(),
                mutation,
                candidate.sourceContext(),
                candidate.targetContext(),
                candidate.sourceResource(),
                candidate.targetResource(),
                candidate.targetResolution().expectedDecision(),
                candidate.targetResolution().evidenceIds(),
                candidate.dependencies(),
                invariants,
                4,
                true,
                candidate.userSelected(),
                candidate.userExcluded(),
                "explicit workflow transition policy; policy=" + candidate.targetResolution().policyFingerprint()));
        return new S7WorkflowSeedGenerationResult(seeds, skipped);
    }

    private static boolean resolvable(WorkflowAuthorizationResolution resolution) {
        return resolution.state() == PolicyResolutionState.RESOLVED_ALLOW
                || resolution.state() == PolicyResolutionState.RESOLVED_DENY;
    }

    private static boolean sameTransitionContext(WorkflowAuthorizationResolution baseline,
                                                 WorkflowAuthorizationResolution target) {
        return baseline.policyFingerprint().equals(target.policyFingerprint())
                && baseline.workflowId().equals(target.workflowId())
                && baseline.principalId().equals(target.principalId())
                && baseline.tenantId().equals(target.tenantId())
                && baseline.resourceId().equals(target.resourceId())
                && baseline.action().equals(target.action())
                && baseline.fromState().equals(target.fromState());
    }

    private static int occurrences(String source, String value) {
        if (source == null || value == null || value.isEmpty()) return 0;
        int count = 0;
        int offset = 0;
        while ((offset = source.indexOf(value, offset)) >= 0) {
            count++;
            offset += value.length();
        }
        return count;
    }
}
