package io.acra.core.active.evidence;

public enum EvidenceStage {
    TEST,
    BASELINE_REQUEST,
    BASELINE_RESPONSE,
    POSITIVE_CONTROL_REQUEST,
    POSITIVE_CONTROL_RESPONSE,
    NEGATIVE_CONTROL_REQUEST,
    NEGATIVE_CONTROL_RESPONSE,
    MUTATION_REQUEST,
    MUTATION_RESPONSE,
    DIFFERENTIAL,
    OBSERVATION
}
