package io.acra.core.active.evidence;

public enum SafetyEventType {
    VALIDATION_ALLOWED,
    VALIDATION_BLOCKED,
    VALIDATION_REQUIRES_CONFIRMATION,
    VALIDATION_INVALID,
    KILL_SWITCH_ENGAGED,
    KILL_SWITCH_RESET,
    BUDGET_RESERVED,
    BUDGET_COMMITTED,
    BUDGET_RELEASED,
    RATE_LIMITED,
    QUEUE_CANCELLED,
    DISPATCH_STARTED,
    DISPATCH_COMPLETED,
    DISPATCH_FAILED
}
