package io.acra.core.openapi;
import io.acra.core.domain.http.HttpMethod;
import java.util.*;
public final class OpenApiImporter {
    private static final Set<String> METHODS=Set.of("get","post","put","patch","delete","head","options","trace");
    public OpenApiDocument importText(String text,String source){if(text==null||text.isBlank())throw new IllegalArgumentException("spec text required");String t=text.stripLeading();return t.startsWith("{")?fromJson(text,source):fromYamlSubset(text,source);}
    @SuppressWarnings("unchecked") private OpenApiDocument fromJson(String text,String source){Object rootObj=MiniJson.parse(text);if(!(rootObj instanceof Map<?,?>))throw new IllegalArgumentException("OpenAPI root must be object");Map<String,Object> root=(Map<String,Object>)rootObj;OpenApiSpecKind kind=root.containsKey("openapi")?OpenApiSpecKind.OPENAPI_3:root.containsKey("swagger")?OpenApiSpecKind.SWAGGER_2:OpenApiSpecKind.UNKNOWN;String version=str(root.get(kind==OpenApiSpecKind.SWAGGER_2?"swagger":"openapi"));String title="";Object info=root.get("info");if(info instanceof Map<?,?> im)title=str(im.get("title"));Map<String,OpenApiSecurityScheme> schemes=parseSchemes(root,kind);List<OpenApiOperation> ops=new ArrayList<>();Object paths=root.get("paths");if(paths instanceof Map<?,?> pm){for(var pe:pm.entrySet()){String path=String.valueOf(pe.getKey());if(!(pe.getValue() instanceof Map<?,?> methods))continue;List<OpenApiParameter> pathParams=parseParameters(methods.get("parameters"));for(var me:methods.entrySet()){String m=String.valueOf(me.getKey()).toLowerCase(Locale.ROOT);if(!METHODS.contains(m)||!(me.getValue() instanceof Map<?,?> opm))continue;List<OpenApiParameter> params=new ArrayList<>(pathParams);params.addAll(parseParameters(opm.get("parameters")));ops.add(new OpenApiOperation(path,HttpMethod.parse(m),str(opm.get("operationId")),strings(opm.get("tags")),params,securityNames(opm.get("security")),responseCodes(opm.get("responses"))));}}}
        return new OpenApiDocument(kind,version,title,ops,schemes,source);}
    private OpenApiDocument fromYamlSubset(String text,String source){OpenApiSpecKind kind=OpenApiSpecKind.UNKNOWN;String version="",title="";List<OpenApiOperation> ops=new ArrayList<>();Map<String,OpenApiSecurityScheme> schemes=new TreeMap<>();String currentPath=null,currentMethod=null,operationId="";List<String> tags=new ArrayList<>();List<OpenApiParameter> params=new ArrayList<>();for(String raw:text.split("\\R")){String line=stripComment(raw);if(line.isBlank())continue;int ind=indent(raw);String tr=line.trim();if(tr.startsWith("openapi:")){kind=OpenApiSpecKind.OPENAPI_3;version=unquote(tr.substring(8).trim());continue;}if(tr.startsWith("swagger:")){kind=OpenApiSpecKind.SWAGGER_2;version=unquote(tr.substring(8).trim());continue;}if(tr.startsWith("title:")&&ind>=2&&title.isBlank()){title=unquote(tr.substring(6).trim());continue;}if(ind==2&&tr.startsWith("/")&&tr.endsWith(":")){flush(ops,currentPath,currentMethod,operationId,tags,params);currentPath=tr.substring(0,tr.length()-1);currentMethod=null;operationId="";tags=new ArrayList<>();params=new ArrayList<>();continue;}if(ind==4&&tr.endsWith(":")){String maybe=tr.substring(0,tr.length()-1).toLowerCase(Locale.ROOT);if(METHODS.contains(maybe)){flush(ops,currentPath,currentMethod,operationId,tags,params);currentMethod=maybe;operationId="";tags=new ArrayList<>();params=new ArrayList<>();continue;}}if(currentMethod!=null&&tr.startsWith("operationId:")){operationId=unquote(tr.substring(12).trim());continue;}if(currentMethod!=null&&tr.startsWith("- name:")){String name=unquote(tr.substring(7).trim());params.add(new OpenApiParameter(name,"",false,""));continue;}if(currentMethod!=null&&tr.startsWith("in:")&&!params.isEmpty()){OpenApiParameter p=params.removeLast();params.add(new OpenApiParameter(p.name(),unquote(tr.substring(3).trim()),p.required(),p.schemaType()));continue;}if(currentMethod!=null&&tr.startsWith("required:")&&!params.isEmpty()){OpenApiParameter p=params.removeLast();params.add(new OpenApiParameter(p.name(),p.location(),Boolean.parseBoolean(tr.substring(9).trim()),p.schemaType()));}}
        flush(ops,currentPath,currentMethod,operationId,tags,params);return new OpenApiDocument(kind,version,title,ops,schemes,source);}
    private static void flush(List<OpenApiOperation> ops,String path,String method,String operationId,List<String> tags,List<OpenApiParameter> params){if(path!=null&&method!=null)ops.add(new OpenApiOperation(path,HttpMethod.parse(method),operationId,tags,params,List.of(),List.of()));}
    @SuppressWarnings("unchecked") private static Map<String,OpenApiSecurityScheme> parseSchemes(Map<String,Object> root,OpenApiSpecKind kind){Map<String,OpenApiSecurityScheme> out=new TreeMap<>();Object container;if(kind==OpenApiSpecKind.OPENAPI_3){Object components=root.get("components");container=components instanceof Map<?,?> c?c.get("securitySchemes"):null;}else container=root.get("securityDefinitions");if(container instanceof Map<?,?> sm)for(var e:sm.entrySet())if(e.getValue() instanceof Map<?,?> v)out.put(String.valueOf(e.getKey()),new OpenApiSecurityScheme(String.valueOf(e.getKey()),str(v.get("type")),str(v.get("scheme")),str(v.get("in")),str(v.get("bearerFormat"))));return out;}
    private static List<OpenApiParameter> parseParameters(Object obj){List<OpenApiParameter> out=new ArrayList<>();if(obj instanceof List<?> l)for(Object x:l)if(x instanceof Map<?,?> m){String type="";Object schema=m.get("schema");if(schema instanceof Map<?,?> sm)type=str(sm.get("type"));if(type.isBlank())type=str(m.get("type"));out.add(new OpenApiParameter(str(m.get("name")),str(m.get("in")),Boolean.TRUE.equals(m.get("required")),type));}return out;}
    private static List<String> securityNames(Object obj){List<String> out=new ArrayList<>();if(obj instanceof List<?> l)for(Object x:l)if(x instanceof Map<?,?> m)for(Object k:m.keySet())out.add(String.valueOf(k));return List.copyOf(out);}
    private static List<String> responseCodes(Object obj){if(obj instanceof Map<?,?> m)return m.keySet().stream().map(String::valueOf).sorted().toList();return List.of();}
    private static List<String> strings(Object obj){if(obj instanceof List<?> l)return l.stream().map(String::valueOf).toList();return List.of();}
    private static String str(Object o){return o==null?"":String.valueOf(o);}
    private static int indent(String s){int n=0;while(n<s.length()&&s.charAt(n)==' ')n++;return n;}
    private static String stripComment(String s){int i=s.indexOf('#');return i<0?s:s.substring(0,i);}
    private static String unquote(String s){if(s.length()>=2&&((s.startsWith("\"")&&s.endsWith("\""))||(s.startsWith("'")&&s.endsWith("'"))))return s.substring(1,s.length()-1);return s;}
}
