package io.acra.core.openapi;
public enum SchemaDriftType { UNDOCUMENTED_ENDPOINT, DOCUMENTED_UNOBSERVED_ENDPOINT, METHOD_MISMATCH, UNDOCUMENTED_PARAMETER, DECLARED_PARAMETER_UNOBSERVED, AUTHENTICATION_MISMATCH, RESPONSE_MISMATCH, UNKNOWN }
